#Project Isengard Messaging
version: '3.8'

services:
  mongo:
    image: mongo:4.2
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1 --bind_ip_all
    volumes:
      - ./mongo_data:/data/db
    networks:
      - internal

  mongo-init-replica:
    image: mongo:4.2
    command: >
      bash -c
      "for i in `seq 1 30`; do
        mongo mongo/rocketchat --eval \"
          rs.initiate({
            _id: 'rs0',
            members: [ { _id: 0, host: 'mongo:27017' } ]
          })
        \"
        && s=$$? && break || s=$$?;
        echo \"Tried $$i times. Waiting 5 secs...\";
        sleep 5;
      done; (exit $$s)"
    depends_on:
      - mongo
    networks:
      - internal

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat?replicaSet=rs0
      ROOT_URL: http://localhost:3000
      PORT: 3000
      MONGO_OPLOG_URL: mongodb://mongo:27017/local?replicaSet=rs0
    depends_on:
      - mongo
      - mongo-init-replica
    ports:
      - "3000:3000"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  mongo_data:
