#Project Isengard Castle - Passwords
version: '3.8'

services:
  vault:
    image: vault:1.10.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
    entrypoint: vault server -config=/vault/config/local.json
    networks:
      - vaultnet

networks:
  vaultnet:
