---
- name: Install Teleport using curl script
  hosts: all
  become: yes
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Teleport
      ansible.builtin.shell: "curl https://goteleport.com/static/install.sh | bash -s 15.3.5"
      args:
        executable: /bin/bash
