---
- name: Upgrade all packages on Ubuntu servers
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Ensure the system is up to date
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'yes'
        force_apt_get: yes
      become: true
      become_user: root

    - name: Clean up unnecessary packages
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
