---
- name: Upgrade all packages on a server
  hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /path/to/keypair1

  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes
      become: true
      become_user: root
