---
- name: Run various shell commands
  hosts: all
  become: true  # Optional, use only if you need elevated privileges

  tasks:
    - name: Change directory to /opt
      command: sh -c "cd /opt"


    - name: Fetch the Docker Install Script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
      register: curl_output
      ignore_errors: true  # In case the URL is unreachable

    - name: Run the Docker Script
      command: sh -c "sh get-docker.sh"

    - name: Enable Docker
      command: sh -c "sytemctl start docker"

    - name: Get Wazuh
      command: git clone https://github.com/wazuh/wazuh-docker.git -b v4.7.3

    - name: Generate Certs
      command: sh -c "docker-compose -f generate-indexer-certs.yml run --rm generator"

    - name: Change directory to /opt
      command: sh -c "cd /wazuh-docker/single-node"

    - name: Run Wazuh
      command: sh -c "docker-compose up -d
