name: Deploy with Ansible

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Select Ansible Playbook'
        required: true
        type: choice
        options:
          - patch.yml
          - upgrade.yml
          - watchtower.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH configuration
        run: |
          echo "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.yml ${{ github.event.inputs.playbook }}
        working-directory: ./ansible
