name: Deploy with Ansible

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Select Ansible Playbook'
        required: true
        type: choice
        options:
          - patch.yml
          - upgrade.yml
          - watchtower.yml

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup SSH with a passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.yml ${{ github.event.inputs.playbook }}
        working-directory: ./ansible
