name: 'Isengard Destroy'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Isengard-Destroy'
    runs-on: ubuntu-latest
    env:
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
    
    defaults:
      run:
        working-directory: ./terraform

      steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-2

    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
